# Generated by Django 4.2.9 on 2024-08-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=500)),
                ('desc', models.TextField(max_length=9000)),
            ],
        ),
    ]
