# Generated by Django 4.2.9 on 2024-08-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aboutProduct',
            field=models.TextField(default='', max_length=9000),
        ),
    ]
