# Generated by Django 4.2.9 on 2024-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sellplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellplans',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
