# Generated by Django 4.2.9 on 2024-08-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_contractinstallment_contractprerecipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=1200)),
                ('UserRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstallments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('InstallmentPrice', models.IntegerField()),
                ('isPayed', models.BooleanField()),
                ('OrderRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
                ('ProductRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
