# Generated by Django 4.2.9 on 2024-08-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_productinstallments'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstallments',
            name='InstallmentIndex',
            field=models.IntegerField(null=True),
        ),
    ]
