# Generated by Django 4.2.9 on 2024-08-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productinstallments_installmentindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='IsEnded',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Code',
            field=models.IntegerField(null=True),
        ),
    ]
