# Generated by Django 4.2.9 on 2024-08-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Code',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
