# Generated by Django 4.2.9 on 2024-09-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyImage', models.TextField(max_length=999999999)),
                ('FirsPageImage', models.TextField(max_length=999999999)),
                ('BackgroundImage', models.TextField(max_length=999999999)),
            ],
        ),
    ]
